name: Check Client

on:
  push:
    branches:
      - "main"

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies 
      working-directory: ./ipsum-client
      run: yarn install --frozen-lockfile

    - name: Run typechecker
      working-directory: ./ipsum-client
      run: yarn typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies 
      working-directory: ./ipsum-client
      run: yarn install --frozen-lockfile

    - name: Run linter
      working-directory: ./ipsum-client
      run: yarn lint