name: Deploy Server

on:
  push:
    tags:
      - server-v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        file: ipsum-server/Dockerfile
        context: ./ipsum-server
        push: true
        tags: dtrifuno/ipsum-server:latest


