name: Deploy Client

on:
  push:
    tags:
      - client-v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: ./ipsum-client
      run: yarn install --frozen-lockfile

    - name: Build client
      working-directory: ./ipsum-client
      run: |
        yarn export
        ls -la out

    - name: Rsync client to server
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: ./ipsum-client/out/
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
