name: Deploy Library

on:
  push:
    tags:
      - library-v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.1

    - name: Install required dependencies only
      working-directory: ./ipsum
      run: poetry install --only main

    - name: Build package
      working-directory: ./ipsum
      run: poetry build

    - name: Publish package to PyPI
      working-directory: ./ipsum
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}