name: Deploy Library

on:
  push:
    tags:
      - library-v*

jobs:
  typecheck-lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - uses: snok/install-poetry@v1
      with:
        version: 1.3.1
    - name: Install dependencies
      working-directory: ./ipsum
      run: poetry install --only main
    - name: Build package
      working-directory: ./ipsum
      run: poetry build
    - name: Publish package to PyPi
      working-directory: ./ipsum
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}